---
- name: Hello world
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Demo debug message
      ansible.builtin.debug:
        msg: "I am demo debug message"

    - name: Create a text file contain hello world
      changed_when: false
      ansible.builtin.shell:
        cmd: "echo 'hello world' > ~/hello_world.txt"
        executable: /bin/bash

- name: Say my name
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create text file contain my name
      changed_when: false
      ansible.builtin.shell:
        cmd: "echo 'isaac yip' > ~/my_name.txt"
        executable: /bin/bash
